### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by tututcr** [pygame-web/pygbag#180]
macos sonoma 14.5
python3.9
pygbag-0.9.2
question：
(base) thome@Thomes-Mac-Studio fushouluo % pygbag main.py

Serving python files from [/Users/thome/PycharmProjects/dishu/fushouluo/build/web]

with no security/performance in mind, i'm just a test tool : don't rely on me

SUMMARY
________________________

# the app folder
app_folder=/Users/thome/PycharmProjects/dishu/fushouluo

# artefacts directory
build_dir=/Users/thome/PycharmProjects/dishu/fushouluo/build/web

# cache directory
cache=/Users/thome/PycharmProjects/dishu/fushouluo/build/web-cache

# the window title and icon name
app_name=fushouluo

# package name, better make it unique
package=web.pygame.fushouluo-1726898195

# icons:  96x96 for desktop, 16x16 for web
icon=favicon.png

# js/wasm provider
cdn=https://pygame-web.github.io/archives/0.9/

now packing application ....

WARNING: No pygbag.ini found! See: https://pygame-web.github.io/wiki/pygbag-configuration
Ignored dirs: []
Ignored files: []
Traceback (most recent call last):
  File "/opt/miniconda3/bin/pygbag", line 8, in <module>
    sys.exit(main())
  File "/Users/thome/.local/lib/python3.9/site-packages/pygbag/app.py", line 592, in main
    asyncio.run(main_run(app_folder, mainscript))
  File "/opt/miniconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/thome/.local/lib/python3.9/site-packages/pygbag/app.py", line 449, in main_run
    await pack.archive(f"{app_name}.apk", app_folder, ignore_dirs, ignore_files, build_dir)
  File "/Users/thome/.local/lib/python3.9/site-packages/pygbag/pack.py", line 93, in archive
    for infolder, fullpath in filter(walked, ignore_dirs, ignore_files):
  File "/Users/thome/.local/lib/python3.9/site-packages/pygbag/filtering.py", line 41, in filter
    if folder.startswith("."):
AttributeError: 'PosixPath' object has no attribute 'startswith'

**Comment by pmp-p** [comment]
thx for the report !
