### ISSUE TITLE
Can't use modules

### ISSUE THREAD

**Issue by ManPython** [pygame-web/pygbag#183]
As I read should be done:
```
dependencies = [
#  "six",
#  "bs4",
#  "markdown-it-py",
#  "pygments",
#  "rich",
#  "mdurl",
#  "textual",
pygame,
pytmx, 
]
```
But pygbag not compiling this but downloading. Event no dependencies  or in.
```
1187: repo['-CDN-']='http://localhost:8000/archives/repo/' does not provide want='View'
1187: repo['-CDN-']='http://localhost:8000/archives/repo/' does not provide want='Control'
635: maybe_wanted=[] known failed aio.pep0723.hint_failed=['View', 'Control']
715: starting shell
1039: 73 lines queued for async eval
going interactive
746: TODO detect input/print to select repl debug
189 : FIXME sync->async->sync import bytecode retry in non interactive
await aio.pep0723.pip_install("pytmx");import pytmx
282: searching pytmx
76: fopen: fetching "https://pypi.org/simple/pytmx/"
76: fopen: fetching "https://files.pythonhosted.org/packages/35/e0/fd0a2d2b93599dec876158fe7fccb8c3e8096844a5a4110dd5bc67377128/PyTMX-3.32-py3-none-any.whl#sha256=4da4c01133dfcb2746cb4e7f46ea1aef21d56119ab044f8f77b9906dea5fbccb"
142: /tmp/PyTMX-3.32-py3-none-any.whl installed
```

**Comment by pmp-p** [comment]
the pep block in an example, in your case it is likely to be

```py
# /// script
# dependencies = [
#  "pygame-ce",
#  "pytmx",
# ]
# ///
```
do not remove the `# ` follow https://peps.python.org/pep-0723/ guide

**Comment by ManPython** [comment]
Thx for support. It's clear but here is case:
Chrome:
```
======  REDIRECT TO DEV HOST http://localhost:8000/archives/repo/  ========
abitag='cp312'
apitag='wasm32_bi_emscripten'


{}
----------------------------------------

656: aio.pep0723.pip_install deps=[]

1214: list_imports len(code)=5013 file=None hint='/data/data/org.python/assets/__main__.py'")
aio.pep0723.Config.pkg_repolist[0]['-CDN-']='http://localhost:8000/archives/repo/'


1153: scan_imports hint='/data/data/org.python/assets/__main__.py' filename='<stdin>' len(code)=5013 ['pygame.base']
635: maybe_wanted=['pygame.base'] known failed aio.pep0723.hint_failed=[]
282: searching pygame.base
76: fopen: fetching "http://localhost:8000/archives/repo/cp312/pygame_static-1.0-cp312-cp312-wasm32_bi_emscripten.whl#"
142: /tmp/pygame_static-1.0-cp312-cp312-wasm32_bi_emscripten.whl installed
254: patching pygame.base
Traceback (most recent call last):
  File "/data/data/org.python/assets/site-packages/aio/pep0723.py", line 268, in do_patches
    platform.patches.pop(dep)()
  File "/data/data/org.python/assets/site-packages/platform_wasm/todo.py", line 318, in patch_pygame
    import pygame.base
  File "/data/data/org.python/assets/site-packages/pygame/__init__.py", line 93, in <module>
    import pygame_static
ImportError: Could not load dynamic lib: /data/data/org.python/assets/build/env/pygame_static.cpython-312-wasm32-emscripten.so
RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
715: starting shell
1039: 213 lines queued for async eval
Loading xpygame from xpygame.apk
    Pygbag Version : 0.9.2
    Template Version : 0.9.0
    Python  : 3.12
    CDN URL : http://localhost:8000//archives/0.9/
    Screen  : 1280x720
    Title   : xpygame
    Folder  : xpygame
    Authors : pgw
    SPDX-License-Identifier: cookiecutter.spdx


1764: __file__='/data/data/org.python/assets/__main__.py' done : now trying user sources
1830: local=None source='' is_py=False hint='main.py'
1867: local=None source='' is_py=False hint='main.py'
404: embed= or sys.argv=['debug']
651: starting EventTarget in a few seconds

Python 3.12.2 (main, Mar  5 2024, 11:18:41) [Clang 19.0.0git (https:/github.com/llvm/llvm-project aec6a04b8e99b42eca431fc0b5 on emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> Task exception was never retrieved
future: <Task finished name='custom_site' coro=<custom_site() done, defined at <console>:52> exception=ImportError('dynamic module does not define module export function (PyInit_pygame_static)')>
Traceback (most recent call last):
  File "<console>", line 67, in custom_site
  File "/data/data/org.python/assets/site-packages/pygame/__init__.py", line 93, in <module>
    import pygame_static
ImportError: dynamic module does not define module export function (PyInit_pygame_static)

KeyboardInterrupt
>>> 
```
On FireFox is going more far but hanged. There is top belt about slow browser by this site.. + stop button.
I'm trying with this as basic for this type projects:
```
# /// script
# dependencies = [
#  "pygame-ce",
#  "pytmx",
#  "cv2",
#  "numpy",
#  "pil",
#  "pillow",
# ]
# ///
```

**Comment by pmp-p** [comment]
maybe you have some .mp3 file in your game folder. Or forgotten some module dep.

Try prepending `--git` to your pygbag command line to use the new deps solver. Also pick only one from "pil"/"pillow" it is the same module. ( Pillow has replaced PIL )

**Comment by ManPython** [comment]
In folder exist mp3 but not used as replaced to .ogg
Can this impact as default packed all in dirs? Then did not expected this.
Will try with `--git`

**Comment by ManPython** [comment]
I deleted any .mp3 and tried `--git`, no changes around, it's working hard and hanged after first screen image.

**Comment by pmp-p** [comment]
This is getting pygame specific , not really pygbag so you will need to publish your project code+assets on github and get help on pygame-ce discord, on pygame-web subchannel.

**Comment by ManPython** [comment]
Still not clear here.. as 

I have this example game with pytmx : https://github.com/eezageeza1976/Tile-Game
Where again `ModuleNotFoundError: No module named 'pytweening'`

```
OK
Please wait ...
807: DEV MODE ON ['http://localhost:8000/archives/repo/']
655: preload_code(len(code)=5027 hint='/data/data/org.python/assets/__main__.py' loaderhome='.')
['/usr/lib/python312.zip', '/usr/lib/python3.12', '/usr/lib/python3.12/lib-dynload', '/usr/lib/python3.12/site-packages', '/data/data/org.python/assets/site-packages', '/data/data/org.python/assets', '.']
200: async_repos ['https://pygame-web.github.io/archives/repo/']
76: fopen: fetching "https://pygame-web.github.io/archives/repo/index-090-cp312.json"
232: http://localhost:8000/#debug


======  REDIRECT TO DEV HOST http://localhost:8000/archives/repo/  ========
abitag='cp312'
apitag='wasm32_bi_emscripten'


76: fopen: fetching "https://pygame-web.github.io/archives/repo/repodata.json"
650: FIXME (this is pyodide maintened stuff, use (auto)PEP723 asap)
651: referenced packages : 184
654: aio.pep0723.check_list aio.pep0723.env=PosixPath('/data/data/org.python/assets/build/env')

----------- computing required packages ----------
392: parse_code() patches loaded : ['matplotlib', 'panda3d', 'wcwidth', 'pygame.base', 'textual']
200: async_repos ['https://pygame-web.github.io/archives/repo/']
76: fopen: fetching "https://pygame-web.github.io/archives/repo/index-090-cp312.json"
232: http://localhost:8000/#debug


======  REDIRECT TO DEV HOST http://localhost:8000/archives/repo/  ========
abitag='cp312'
apitag='wasm32_bi_emscripten'


{}
----------------------------------------

656: aio.pep0723.pip_install deps=[]

1214: list_imports len(code)=5027 file=None hint='/data/data/org.python/assets/__main__.py'")
aio.pep0723.Config.pkg_repolist[0]['-CDN-']='http://localhost:8000/archives/repo/'


1153: scan_imports hint='/data/data/org.python/assets/__main__.py' filename='<stdin>' len(code)=5027 ['pygame.base']
635: maybe_wanted=['pygame.base'] known failed aio.pep0723.hint_failed=[]
282: searching pygame.base
76: fopen: fetching "http://localhost:8000/archives/repo/cp312/pygame_static-1.0-cp312-cp312-wasm32_bi_emscripten.whl#"
142: /tmp/pygame_static-1.0-cp312-cp312-wasm32_bi_emscripten.whl installed
254: patching pygame.base
pygame-ce 2.5.0.dev1 (SDL 2.28.4, Python 3.12.2)
https://github.com/pygame-web/pygbag/issues/16
    applying: use aio green thread for pygame.time.set_timer









sys._emscripten_info(emscripten_version=(3, 1, 56), runtime='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:135.0) Gecko/20100101 Firefox/135.0', pthreads=False, shared_memory=False)
715: starting shell
1039: 213 lines queued for async eval
Loading tile-game-main from tile-game-main.apk
    Pygbag Version : 0.9.2
    Template Version : 0.9.0
    Python  : 3.12
    CDN URL : http://localhost:8000//archives/0.9/
    Screen  : 1280x720
    Title   : tile-game-main
    Folder  : tile-game-main
    Authors : pgw
    SPDX-License-Identifier: cookiecutter.spdx


1764: __file__='/data/data/org.python/assets/__main__.py' done : now trying user sources
1830: local=None source='' is_py=False hint='main.py'
1867: local=None source='' is_py=False hint='main.py'
404: embed= or sys.argv=['debug']
651: starting EventTarget in a few seconds

Python 3.12.2 (main, Mar  5 2024, 11:18:41) [Clang 19.0.0git (https:/github.com/llvm/llvm-project aec6a04b8e99b42eca431fc0b5 on emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> 309: assets found : 0
364: EventTarget delayed by loader
/data/data/org.python/assets/site-packages/pygame/sysfont.py:235: UserWarning: no fc_cache font cache file at /data/data/tile-game-main/assets/fc_cache
  warnings.warn(f"no fc_cache font cache file at {fc_cache}")
690: : runpy(main=PosixPath('/data/data/tile-game-main/assets/main.py'))
655: preload_code(len(code)=11580 hint=PosixPath('/data/data/tile-game-main/assets/main.py') loaderhome='.')
654: aio.pep0723.check_list aio.pep0723.env=PosixPath('/data/data/org.python/assets/build/env')

----------- computing required packages ----------
{
    "dependencies": [
        "pygame-ce",
        "pytmx",
        "pytweening"
    ]
}
282: searching pygame_ce
282: searching pytmx
76: fopen: fetching "https://pypi.org/simple/pytmx/"
76: fopen: fetching "https://files.pythonhosted.org/packages/35/e0/fd0a2d2b93599dec876158fe7fccb8c3e8096844a5a4110dd5bc67377128/PyTMX-3.32-py3-none-any.whl#sha256=4da4c01133dfcb2746cb4e7f46ea1aef21d56119ab044f8f77b9906dea5fbccb"
142: /tmp/PyTMX-3.32-py3-none-any.whl installed
282: searching pytweening
76: fopen: fetching "https://pypi.org/simple/pytweening/"
----------------------------------------

656: aio.pep0723.pip_install deps=['pygame_ce', 'pytmx', 'pytweening']

1214: list_imports len(code)=11580 file=None hint=PosixPath('/data/data/tile-game-main/assets/main.py')")
aio.pep0723.Config.pkg_repolist[0]['-CDN-']='http://localhost:8000/archives/repo/'


1153: scan_imports hint=PosixPath('/data/data/tile-game-main/assets/main.py') filename='<stdin>' len(code)=11580 ['settings', 'sprites', 'tilemap']
1187: repo['-CDN-']='http://localhost:8000/archives/repo/' does not provide want='settings'
1187: repo['-CDN-']='http://localhost:8000/archives/repo/' does not provide want='sprites'
1187: repo['-CDN-']='http://localhost:8000/archives/repo/' does not provide want='tilemap'
635: maybe_wanted=[] known failed aio.pep0723.hint_failed=['settings', 'sprites', 'tilemap']
282: searching pygame_ce
282: searching pytweening
76: fopen: fetching "https://pypi.org/simple/pytweening/"
715: starting shell
1039: 303 lines queued for async eval
going interactive
746: TODO detect input/print to select repl debug
189 : FIXME sync->async->sync import bytecode retry in non interactive
await aio.pep0723.pip_install("pytweening");import pytweening
282: searching pytweening
76: fopen: fetching "https://pypi.org/simple/pytweening/"
<class 'aio.sentinel'> ∅
Traceback (most recent call last):
  File "/data/data/org.python/assets/site-packages/aio/toplevel.py", line 200, in interact_step
    self.rv = await self.shell.coro.pop(0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/org.python/assets/site-packages/aio/toplevel.py", line 109, in import_now
    vars(__import__("__main__"))[want] = __import__(want)
                                         ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pytweening'
```

The base code to run.

```
# Mini Crusader Game
import pygame as pg
import sys
from os import path
from settings import *
from sprites import *
from tilemap import *

# /// script
# dependencies = [
#  "pygame-ce",
#  "pytmx",
#  "pytweening"
# ]
# ///
import asyncio

# HUD functions
def draw_player_health(surf, x, y, pct):
    if pct < 0:
        pct = 0
    BAR_LENGTH = 100
    BAR_HEIGHT = 20
    fill = pct * BAR_LENGTH
    outline_rect = pg.Rect(x, y, BAR_LENGTH, BAR_HEIGHT)
    fill_rect = pg.Rect(x, y, fill, BAR_HEIGHT)
    if pct > 0.6:
        col = GREEN
    elif pct > 0.3:
        col = YELLOW
    else:
        col = RED
    pg.draw.rect(surf, col, fill_rect)
    pg.draw.rect(surf, WHITE, outline_rect, 2)

class Game:
    def __init__(self):
        pg.mixer.pre_init(44100, -16, 1, 2048)
        pg.init()
        self.screen = pg.display.set_mode((WIDTH, HEIGHT))
        pg.display.set_caption(TITLE)
        self.clock = pg.time.Clock()
        pg.key.set_repeat(500, 100)
        self.load_data()

    def draw_text(self, text, font_name, size, color, x, y, align="nw"):
        font = pg.font.Font(font_name, size)
        text_surface = font.render(text, True, color)
        text_rect = text_surface.get_rect()
        if align == "nw":
            text_rect.topleft = (x, y)
        if align == "ne":
            text_rect.topright = (x, y)
        if align == "sw":
            text_rect.bottomleft = (x, y)
        if align == "se":
            text_rect.bottomright = (x, y)
        if align == "n":
            text_rect.midtop = (x, y)
        if align == "s":
            text_rect.midbottom = (x, y)
        if align == "e":
            text_rect.midright = (x, y)
        if align == "w":
            text_rect.midleft = (x, y)
        if align == "center":
            text_rect.center = (x, y)
        self.screen.blit(text_surface, text_rect)

    def load_data(self):
        game_folder = path.dirname(__file__)
        img_folder = path.join(game_folder, 'img')
        self.map_folder = path.join(game_folder, 'maps')
        snd_folder = path.join(game_folder, 'snd')
        music_folder = path.join(game_folder, 'music')
        self.title_font = path.join(img_folder, 'ZOMBIE.TTF')
        self.hud_font = path.join(img_folder, 'Impacted2.0.ttf')
        self.dim_screen = pg.Surface(self.screen.get_size()).convert_alpha()
        self.dim_screen.fill((0, 0, 0, 190))
        self.player_img = pg.image.load(path.join(img_folder, PLAYER_IMG)).convert_alpha()
        self.bullet_images = {}
        self.bullet_images['lg'] = pg.image.load(path.join(img_folder, BULLET_IMG)).convert_alpha()
        self.bullet_images['sm'] = pg.transform.scale(self.bullet_images['lg'], (10, 10))
        self.mob_img = pg.image.load(path.join(img_folder, MOB_IMG)).convert_alpha()
        self.splat = pg.image.load(path.join(img_folder, MOB_SPLAT)).convert_alpha()
        self.splat = pg.transform.scale(self.splat, (64, 64))
        self.gun_flashes = []
        for img in MUZZLE_FLASHES:
            self.gun_flashes.append(pg.image.load(path.join(img_folder, img)).convert_alpha())
        self.item_images = {}
        for item in ITEM_IMAGES:
            self.item_images[item] = pg.image.load(path.join(img_folder, ITEM_IMAGES[item])).convert_alpha()
        # Sound loading
        pg.mixer.music.load(path.join(music_folder, BG_MUSIC))
        self.effects_sounds = {}
        for snd_type in EFFECTS_SOUNDS:
            self.effects_sounds[snd_type] = pg.mixer.Sound(path.join(snd_folder, EFFECTS_SOUNDS[snd_type]))
        self.weapon_sounds = {}
        for weapon in WEAPON_SOUNDS:
            self.weapon_sounds[weapon] = []
            for snd in WEAPON_SOUNDS[weapon]:
                s = pg.mixer.Sound(path.join(snd_folder, snd))
                s.set_volume(0.3)
                self.weapon_sounds[weapon].append(s)
        self.zombie_moan_sounds = []
        for snd in ZOMBIE_MOAN_SOUNDS:
            s = pg.mixer.Sound(path.join(snd_folder, snd))
#            s.set_volume(0.1)
            self.zombie_moan_sounds.append(s)
        self.player_hit_sounds = []
        for snd in PLAYER_HIT_SOUNDS:
            self.player_hit_sounds.append(pg.mixer.Sound(path.join(snd_folder, snd)))
        self.zombie_hit_sounds = []
        for snd in ZOMBIE_HIT_SOUNDS:
            self.zombie_hit_sounds.append(pg.mixer.Sound(path.join(snd_folder, snd)))


    def new(self):
        # initialize all variables and do all the setup for a new game
        self.current_level = 0
        self.level_complete = False
        self.all_sprites = pg.sprite.LayeredUpdates()
        self.walls = pg.sprite.Group()
        self.mobs = pg.sprite.Group()
        self.bullets = pg.sprite.Group()
        self.items = pg.sprite.Group()
        self.map = TiledMap(path.join(self.map_folder, LEVEL_MAPS[self.current_level]))
        self.map_img = self.map.make_map()
        self.map_rect = self.map_img.get_rect()
        for tile_object in self.map.tmxdata.objects:
            obj_center = vec(tile_object.x + tile_object.width / 2,
                             tile_object.y + tile_object.height / 2)
            if tile_object.name == 'player':
                self.player = Player(self, obj_center.x, obj_center.y)
            if tile_object.name == 'zombie':
                Mob(self, obj_center.x, obj_center.y)
            if tile_object.name == 'Wall':
                Obsticle(self, tile_object.x, tile_object.y,
                         tile_object.width, tile_object.height)
            if tile_object.name in ['health', 'shotgun']:
                Item(self, obj_center, tile_object.name)
        self.camera = Camera(self.map.width, self.map.height)
        self.paused = False
        self.effects_sounds['level_start'].play()

    def next_level(self):
        self.current_level += 1
        self.level_complete = False
        self.all_sprites = pg.sprite.LayeredUpdates()
        self.walls = pg.sprite.Group()
        self.mobs = pg.sprite.Group()
        self.bullets = pg.sprite.Group()
        self.items = pg.sprite.Group()
        try:
            self.map = TiledMap(path.join(self.map_folder, LEVEL_MAPS[self.current_level]))
        except:
            self.playing = False
        self.map_img = self.map.make_map()
        self.map_rect = self.map_img.get_rect()
        for tile_object in self.map.tmxdata.objects:
            obj_center = vec(tile_object.x + tile_object.width / 2,
                             tile_object.y + tile_object.height / 2)
            if tile_object.name == 'player':
                self.player = Player(self, obj_center.x, obj_center.y)
            if tile_object.name == 'zombie':
                Mob(self, obj_center.x, obj_center.y)
            if tile_object.name == 'Wall':
                Obsticle(self, tile_object.x, tile_object.y,
                         tile_object.width, tile_object.height)
            if tile_object.name in ['health', 'shotgun']:
                Item(self, obj_center, tile_object.name)
        self.camera = Camera(self.map.width, self.map.height)
        self.paused = False
        self.effects_sounds['level_start'].play()

    def run(self):
        # game loop - set self.playing = False to end the game
        self.playing = True
        pg.mixer.music.play(loops=-1)
        while self.playing:
            self.dt = self.clock.tick(FPS) / 1000
            self.events()
            if not self.paused:
                self.update()
            self.draw()
            if self.level_complete:
                self.next_level()

    def quit(self):
        pg.quit()
        sys.exit()

    def update(self):
        # update portion of the game loop
        self.all_sprites.update()
        self.camera.update(self.player)
        # Game Over
        if len(self.mobs) == 0:
            #self.playing = False
            self.level_complete = True
        # Player hits items
        hits = pg.sprite.spritecollide(self.player, self.items, False)
        for hit in hits:
            if hit.type == 'health' and self.player.health < PLAYER_HEALTH:
                self.player.add_health(HEALTH_PACK_AMOUNT)
                hit.kill()
                self.effects_sounds['health_up'].play()
            if hit.type == 'shotgun':
                hit.kill()
                self.effects_sounds['gun_pickup'].play()
                self.player.weapon = 'shotgun'
        # mobs hit player
        hits = pg.sprite.spritecollide(self.player, self.mobs, False, collide_hit_rect)
        for hit in hits:
            if random() < 0.7:
                choice(self.player_hit_sounds).play()
            self.player.health -= MOB_DAMAGE
            hit.vel = vec(0, 0)
            if self.player.health <= 0:
                self.playing = False
        if hits:
            self.player.hit()
            self.player.pos += vec(MOB_KNOCKBACK, 0).rotate(-hits[0].rot)
        # bullets hit mobs
        hits = pg.sprite.groupcollide(self.mobs, self.bullets, False, True)
        for mob in hits:
            for bullet in hits[mob]:
                mob.health -= bullet.damage
            mob.vel = vec(0, 0)

    def draw_grid(self):
        for x in range(0, WIDTH, TILESIZE):
            pg.draw.line(self.screen, LIGHTGREY, (x, 0), (x, HEIGHT))
        for y in range(0, HEIGHT, TILESIZE):
            pg.draw.line(self.screen, LIGHTGREY, (0, y), (WIDTH, y))

    def draw(self):
        pg.display.set_caption("{:.2f}".format(self.clock.get_fps()))

        self.screen.blit(self.map_img, self.camera.apply_rect(self.map_rect))
        for sprite in self.all_sprites:
            if isinstance(sprite, Mob):
                sprite.draw_health()
            self.screen.blit(sprite.image, self.camera.apply(sprite))
        # HUD function
        draw_player_health(self.screen, 10, 10, self.player.health / PLAYER_HEALTH)
        self.draw_text('Zombies: {}'.format(len(self.mobs)), self.hud_font, 30, WHITE,
                       WIDTH - 10, 10, align='ne')
        # Paused screen
        if self.paused:
            self.screen.blit(self.dim_screen, (0, 0))
            self.draw_text("Paused", self.title_font, 105, RED,
                           WIDTH / 2, HEIGHT / 2, align='center')

        pg.display.flip()

    def events(self):
        # catch all events here
        for event in pg.event.get():
            if event.type == pg.QUIT:
                self.quit()
            if event.type == pg.KEYDOWN:
                if event.key == pg.K_ESCAPE:
                    self.quit()
                if event.key == pg.K_p:
                    self.paused = not self.paused

    def show_start_screen(self):
        pass

    def show_go_screen(self):
        self.screen.fill(BLACK)
        self.draw_text('GAME OVER', self.title_font, 100, RED,
                       WIDTH / 2, HEIGHT / 2, align='center')
        self.draw_text('Press any key', self.title_font, 75, WHITE,
                       WIDTH / 2, HEIGHT * 3/4, align='center')
        pg.display.flip()
        self.wait_for_key()

    def wait_for_key(self):
        pg.event.wait()
        waiting = True
        while waiting:
            self.clock.tick(FPS)
            for event in pg.event.get():
                if event.type == pg.QUIT:
                    waiting = False
                    self.quit()
                if event.type == pg.KEYUP:
                    waiting = False

# create the game object
g = Game()
g.show_start_screen()
async def main():
    while True:
        g.new()
        g.run()
        g.show_go_screen()

#if __name__ == '__main__':
asyncio.run(main())
```

I'm trying to show something simple that pygbag and webasm working very hard with pytmx..

**Comment by pmp-p** [comment]
as you can see there https://pypi.org/project/pytweening/#files pytweening has no wheel available to download. Maybe it is C compiled code or old distribution mode. in that latter case you can try to put the files next to your main.py.

pytmx works very well with pygbag eg https://pmp-p.github.io/pydew-valley-uzh-pygbag/?cpython3.12

**Comment by ManPython** [comment]
I will try study case with pydew-valley-uzh-pygbag depend pytmx coz still no success in simple case.

**Comment by ManPython** [comment]
Can't confirm build by pydew-valley-uzh-pygbag coz some issues.
https://github.com/pmp-p/pydew-valley-uzh-pygbag/issues/4
