### ISSUE TITLE
pygame_gui: The FreeType 2 library hasn't been initialized

### ISSUE THREAD

**Issue by gabriel-v** [pygame-web/pygbag#62]
When trying to install and run pygame_gui, more specifically with [this fork i found here](https://github.com/pmp-p/pygame-gui-wasm), I run into this error:

```
Traceback (most recent call last):
  File "/data/data/interfatza-pygame-gui/assets/pygame_gui/core/utility.py", line 405, in load
    self.loaded_font = Font(self.location, self.size, resolution=72)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The FreeType 2 library hasn't been initialized
```

I can reproduce this in the `#debug` terminal in the browser:

```
>>> import pygame.freetype
>>> pygame.freetype.init()
>>> pygame.freetype.get_init()
True
>>> pygame.freetype.Font('pygame_gui_data/FiraCode-Regular.ttf')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
RuntimeError: The FreeType 2 library hasn't been initialized
>>> 
```

After a quick check, the problem seems to be [a reality check in this C header](https://github.com/pygame/pygame/blob/93a907c81e79558ed3a067c1726381da0a24020c/src_c/freetype/ft_wrap.h#L248) that seems to be caused by [threading issues](https://stackoverflow.com/questions/18580810/library-not-initialized-in-python-pygame) - so it seems that async io is interfering with the C library bindings?

I also [tried wrapping](https://github.com/gabriel-v/python-wasm-pygame-experiments/blob/db9fe41fbb1c5926ee955908c1d6bde3d5c45ce1/src/interfatza-pygame-gui/superduperfont.py#L4) the new `pygame.freetype.Font` class using the old `pygame.font.Font` class, but I'm not smart enough to do it correctly, so the text is not showing up. 

##### Questions
- did you manage to get the fork running?
- do you think the existing freetype bindings could be used with asyncio in pygbag?
- do you have any tips for trying to implement freetype using the old pygame.font and trick pygame_gui that way?

Thanks!

**Comment by pmp-p** [comment]
no, i tried but i did not get it running but it was at the tech demo time so maybe i could have a fresh look 
 But no so soon.as i tend to spend time on modules i know that can be fixed very quickly and if they can demonstrate a usefull feature.

 There are numerous GUI around and if i would have to choose one it would probably be https://lvgl.io which is small,  written in C, really made for framebuffers, backed by an org. and have bindings for MicroPython, WaPy and soon Nim. I don't think games need guis but editors instead ( like nodezator ).

freetype both old and new have already some open issues anyway. 
most likely due to all of them relying on OS for building a font map like on issue referenced here https://github.com/pygame-web/pygbag/issues/60
